#[cfg(all(test, feature = "sodium-tests"))]
mod sodium_cross_checks {
    // 1) Include libsodium bindings generated by bindgen.
    //    This must appear near the top so we can call them in tests.
    #![allow(unused)]
    #![allow(non_upper_case_globals)]
    include!(concat!(env!("OUT_DIR"), "/sodium_bindings.rs"));

    use std::{ffi::c_void, ptr::null_mut, str::from_utf8};

    // 2) Bring in your crate’s “SoftwareProvider” test environment
    use crate::{
        common::{
            config::{KeyPairSpec, KeySpec},
            crypto::algorithms::{
                encryption::{AsymmetricKeySpec, Cipher},
                hashes::CryptoHash,
            },
            factory,
            traits::key_handle::KeyHandleImpl,
            KeyHandle, KeyPairHandle,
        },
        tests::TestStore,
    };

    static mut STORE: std::sync::LazyLock<TestStore> = std::sync::LazyLock::new(TestStore::new);

    const OPSLIMIT: u64 = 3;
    const MEMLIMIT: usize = 65536;
    const ALG: i32 = crypto_pwhash_argon2id_ALG_ARGON2ID13 as i32;

    // -------------------------------------------------------------------------
    // UTILITY: libsodium initialization
    // -------------------------------------------------------------------------
    fn init_sodium() {
        unsafe {
            if sodium_init() < 0 {
                panic!("Failed to initialize libsodium");
            }
        }
    }

    // -------------------------------------------------------------------------
    // MODULE A: KEY PAIR CROSS-CHECK (ED25519)
    // -------------------------------------------------------------------------
    mod key_pair_cross_check {
        use super::*;

        // -------------- Utility: Create Ed25519 Key Pair in Rust --------------
        fn create_rust_ed25519_key_pair() -> KeyPairHandle {
            let impl_config = unsafe { STORE.impl_config().clone() };
            let mut provider = factory::create_provider_from_name("SoftwareProvider", impl_config)
                .expect("Failed to create provider for Ed25519");

            // Adjust if your code references Ed25519 differently
            let spec = KeyPairSpec {
                asym_spec: AsymmetricKeySpec::Curve25519,
                cipher: None,
                signing_hash: CryptoHash::Sha2_256,
                ephemeral: true,
                non_exportable: false,
            };
            provider
                .create_key_pair(spec)
                .expect("Failed to create Ed25519 keypair in Rust")
        }

        // -------------- Utility: Create Ed25519 Key Pair in libsodium --------------
        unsafe fn create_sodium_ed25519_key_pair() -> (Vec<u8>, Vec<u8>) {
            let mut pk = vec![0u8; crypto_sign_ed25519_PUBLICKEYBYTES as usize];
            let mut sk = vec![0u8; crypto_sign_ed25519_SECRETKEYBYTES as usize];
            crypto_sign_ed25519_keypair(pk.as_mut_ptr(), sk.as_mut_ptr());
            (pk, sk)
        }

        // ---------- 1) cross_check_sign_and_verify (Ed25519) ----------
        #[test]
        fn cross_check_sign_and_verify() {
            init_sodium();
            let message = b"Cross-check sign/verify with libsodium <-> Rust";

            // -- (A) Generate key in Rust, verify signature in libsodium --
            let rust_keypair = create_rust_ed25519_key_pair();
            let rust_signature = rust_keypair.sign_data(message).expect("Rust sign failed");
            let rust_public_key = rust_keypair
                .get_public_key()
                .expect("Failed to get Rust Ed25519 public key");

            unsafe {
                let verify_res = crypto_sign_ed25519_verify_detached(
                    rust_signature.as_ptr(),
                    message.as_ptr(),
                    message.len() as u64,
                    rust_public_key.as_ptr(),
                );
                assert_eq!(
                    verify_res, 0,
                    "libsodium verify failed for signature produced by Rust"
                );
            }

            // -- (B) Generate key in libsodium, verify signature in Rust --
            let (sodium_pk, sodium_sk) = unsafe { create_sodium_ed25519_key_pair() };
            let mut sodium_signature = vec![0u8; crypto_sign_ed25519_BYTES as usize];

            unsafe {
                crypto_sign_ed25519_detached(
                    sodium_signature.as_mut_ptr(),
                    null_mut(),
                    message.as_ptr(),
                    message.len() as u64,
                    sodium_sk.as_ptr(),
                );
            }

            // import public key into Rust
            let impl_config = unsafe { STORE.impl_config().clone() };
            let mut provider = factory::create_provider_from_name("SoftwareProvider", impl_config)
                .expect("Failed to create provider for cross-check verify");

            let spec = KeyPairSpec {
                asym_spec: AsymmetricKeySpec::Curve25519,
                cipher: None,
                signing_hash: CryptoHash::Sha2_256,
                ephemeral: true,
                non_exportable: false,
            };
            let rust_public_handle = provider
                .import_public_key(spec, &sodium_pk)
                .expect("Failed to import libsodium public key into Rust");

            let rust_verify_res = rust_public_handle
                .verify_signature(message, &sodium_signature)
                .expect("Rust verification call failed");
            assert!(
                rust_verify_res,
                "Rust verify of libsodium signature should succeed"
            );
        }

        // ---------- 2) cross_check_verify_with_wrong_data (Ed25519) ----------
        #[test]
        fn cross_check_verify_with_wrong_data() {
            init_sodium();
            let data = b"Data to sign";
            let wrong_data = b"Wrong data";

            // sign in Rust
            let rust_keypair = create_rust_ed25519_key_pair();
            let rust_signature = rust_keypair.sign_data(data).expect("Rust sign failed");
            let rust_public_key = rust_keypair
                .get_public_key()
                .expect("Failed to get Rust public key");

            // Attempt to verify in libsodium with wrong data
            unsafe {
                let verify_res = crypto_sign_ed25519_verify_detached(
                    rust_signature.as_ptr(),
                    wrong_data.as_ptr(),
                    wrong_data.len() as u64,
                    rust_public_key.as_ptr(),
                );
                // libsodium returns 0 on success, anything else on fail
                assert_ne!(
                    verify_res, 0,
                    "libsodium verify should fail with wrong data"
                );
            }
        }

        // ---------- 3) cross_check_verify_with_wrong_key (Ed25519) ----------
        #[test]
        fn cross_check_verify_with_wrong_key() {
            init_sodium();
            let data = b"Data to sign";

            // Key1 for signing
            let keypair1 = create_rust_ed25519_key_pair();
            let signature1 = keypair1.sign_data(data).expect("Rust sign failed");

            // Key2 for verification
            let keypair2 = create_rust_ed25519_key_pair();
            let pk2 = keypair2.get_public_key().expect("Failed to get Rust pk2");

            // libsodium verify signature1 with pk2
            unsafe {
                let verify_res = crypto_sign_ed25519_verify_detached(
                    signature1.as_ptr(),
                    data.as_ptr(),
                    data.len() as u64,
                    pk2.as_ptr(),
                );
                assert_ne!(verify_res, 0, "libsodium verify should fail with wrong key");
            }
        }

        // ---------- 4) cross_check_get_public_key (Ed25519) ----------
        #[test]
        fn cross_check_get_public_key() {
            init_sodium();
            let keypair = create_rust_ed25519_key_pair();
            let rust_public_key = keypair
                .get_public_key()
                .expect("Failed to get Rust public key");
            assert!(
                !rust_public_key.is_empty(),
                "Public key should not be empty"
            );

            // Validate size for libsodium Ed25519
            assert_eq!(
                rust_public_key.len(),
                crypto_sign_ed25519_PUBLICKEYBYTES as usize,
                "Mismatch in public key size"
            );
        }

        // ---------- 5) cross_check_sign_with_public_only_key (Ed25519) ----------
        #[test]
        fn cross_check_sign_with_public_only_key() {
            init_sodium();

            // Generate a full key in Rust
            let full_keypair = create_rust_ed25519_key_pair();
            let rust_pub = full_keypair
                .get_public_key()
                .expect("get_public_key failed");

            // Create a "public-only" handle in Rust
            // (In libsodium, you can't sign with public only, so we'll just
            //  confirm Rust fails to sign if the private portion is missing.)
            let impl_config = unsafe { STORE.impl_config().clone() };
            let mut provider = factory::create_provider_from_name("SoftwareProvider", impl_config)
                .expect("Create provider failed");
            let spec = KeyPairSpec {
                asym_spec: AsymmetricKeySpec::Curve25519,
                cipher: None,
                signing_hash: CryptoHash::Sha2_256,
                ephemeral: true,
                non_exportable: false,
            };
            let public_only_handle = provider
                .import_public_key(spec, &rust_pub)
                .expect("Failed to create public-only key handle");

            let sign_result = public_only_handle.sign_data(b"Data to sign");
            assert!(
                sign_result.is_err(),
                "Signing should fail with public-only key"
            );
        }

        // ---------- 6) cross_check_verify_with_public_only_key (Ed25519) ----------
        #[test]
        fn cross_check_verify_with_public_only_key() {
            init_sodium();

            // Create full Ed25519 key in Rust
            let full_keypair = create_rust_ed25519_key_pair();
            let rust_pub = full_keypair
                .get_public_key()
                .expect("get_public_key failed");

            let data = b"Data to sign";
            let signature = full_keypair.sign_data(data).expect("Rust sign failed");

            // Create a "public-only" handle from that public key
            let impl_config = unsafe { STORE.impl_config().clone() };
            let mut provider = factory::create_provider_from_name("SoftwareProvider", impl_config)
                .expect("Create provider failed");
            let spec = KeyPairSpec {
                asym_spec: AsymmetricKeySpec::Curve25519,
                cipher: None,
                signing_hash: CryptoHash::Sha2_256,
                ephemeral: true,
                non_exportable: false,
            };
            let pub_only_handle = provider
                .import_public_key(spec, &rust_pub)
                .expect("Failed to create public-only handle");

            // Verify signature with public-only
            let verified = pub_only_handle
                .verify_signature(data, &signature)
                .expect("verification failed");
            assert!(verified, "Signature should be valid with public-only key");
        }

        // ---------- 7) cross_check_id_method (Ed25519) ----------
        #[test]
        fn cross_check_id_method() {
            init_sodium();

            let keypair = create_rust_ed25519_key_pair();
            let key_id = keypair.id().expect("Failed to get key ID");
            assert!(
                !key_id.is_empty(),
                "Key ID should not be empty for cross-check"
            );
        }
    }

    // -------------------------------------------------------------------------
    // MODULE B: KEY HANDLE CROSS-CHECK (AES-GCM-256)
    // -------------------------------------------------------------------------
    mod key_handle_cross_check {
        use ring::aead::MAX_TAG_LEN;

        use super::*;

        /// Create an AES-GCM-256 key in Rust
        fn create_rust_aesgcm256_key() -> KeyHandle {
            let impl_config = unsafe { STORE.impl_config().clone() };
            let mut provider = factory::create_provider_from_name("SoftwareProvider", impl_config)
                .expect("Failed to create provider");

            let spec = KeySpec {
                cipher: Cipher::AesGcm256,
                ..Default::default()
            };
            provider
                .create_key(spec)
                .expect("Failed to create AES-GCM-256 key in Rust")
        }

        // ---------- 1) cross_check_encrypt_decrypt_data ----------
        #[test]
        fn cross_check_encrypt_decrypt_data() {
            init_sodium();

            // If AES-GCM is CPU-dependent, check:
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available in libsodium build or CPU");
            }

            let plaintext = b"Cross-check standard encryption/decryption";
            let rust_handle = create_rust_aesgcm256_key();

            // Rust encrypt
            let (ciphertext, nonce) = rust_handle
                .encrypt_data(plaintext)
                .expect("Rust encrypt_data failed");

            // Extract raw key from Rust
            let rust_raw_key = rust_handle
                .implementation
                .extract_key()
                .expect("Failed to extract raw key from Rust");
            assert_eq!(rust_raw_key.len(), 32);

            // libsodium decrypt
            unsafe {
                let mut decrypted = vec![0u8; ciphertext.len()];
                let mut decrypted_len: u64 = 0;
                let aad = []; // No additional data
                let dec_res = crypto_aead_aes256gcm_decrypt(
                    decrypted.as_mut_ptr(),
                    &mut decrypted_len,
                    null_mut(),
                    ciphertext.as_ptr(),
                    ciphertext.len() as u64,
                    aad.as_ptr(),
                    aad.len() as u64,
                    nonce.as_ptr(),
                    rust_raw_key.as_ptr(),
                );
                assert_eq!(dec_res, 0, "libsodium decrypt failed");
                decrypted.truncate(decrypted_len as usize - MAX_TAG_LEN);

                assert_eq!(
                    &decrypted, plaintext,
                    "libsodium->decrypted text mismatch with original"
                );
            }
        }

        // ---------- 2) cross_check_encrypt_decrypt_empty_data ----------
        #[test]
        fn cross_check_encrypt_decrypt_empty_data() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available in libsodium build/CPU");
            }
            let rust_handle = create_rust_aesgcm256_key();
            let plaintext = &[];

            let (ciphertext, nonce) = rust_handle
                .encrypt_data(plaintext)
                .expect("Rust encrypt empty data failed");

            let rust_key = rust_handle
                .implementation
                .extract_key()
                .expect("Failed to extract Rust AES key");

            unsafe {
                let mut decrypted = vec![0u8; ciphertext.len()];
                let mut decrypted_len: u64 = 0;
                let dec_res = crypto_aead_aes256gcm_decrypt(
                    decrypted.as_mut_ptr(),
                    &mut decrypted_len,
                    null_mut(),
                    ciphertext.as_ptr(),
                    ciphertext.len() as u64,
                    [].as_ptr(),
                    0,
                    nonce.as_ptr(),
                    rust_key.as_ptr(),
                );
                assert_eq!(dec_res, 0);
                decrypted.truncate(decrypted_len as usize - MAX_TAG_LEN);

                assert_eq!(&decrypted, plaintext, "Empty data mismatch");
            }
        }

        // ---------- 3) cross_check_decrypt_with_wrong_key ----------
        #[test]
        fn cross_check_decrypt_with_wrong_key() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available");
            }

            let plaintext = b"Data encrypted with key 1";

            // Key #1 (encrypt)
            let rust_handle1 = create_rust_aesgcm256_key();
            let (ciphertext, nonce) = rust_handle1
                .encrypt_data(plaintext)
                .expect("Rust encrypt_data failed");
            // Key #2 (attempt to decrypt)
            let rust_handle2 = create_rust_aesgcm256_key();
            let raw_key2 = rust_handle2
                .implementation
                .extract_key()
                .expect("Extract key #2 failed");

            // libsodium tries to decrypt with the wrong key
            unsafe {
                let mut decrypted = vec![0u8; ciphertext.len()];
                let mut dec_len: u64 = 0;
                let aad = [];
                let dec_res = crypto_aead_aes256gcm_decrypt(
                    decrypted.as_mut_ptr(),
                    &mut dec_len,
                    null_mut(),
                    ciphertext.as_ptr(),
                    ciphertext.len() as u64,
                    aad.as_ptr(),
                    aad.len() as u64,
                    nonce.as_ptr(),
                    raw_key2.as_ptr(),
                );
                // dec_res != 0 => failure
                assert_ne!(
                    dec_res, 0,
                    "libsodium decryption should fail with the wrong key"
                );
            }
        }

        // ---------- 4) cross_check_decrypt_modified_ciphertext ----------
        #[test]
        fn cross_check_decrypt_modified_ciphertext() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available");
            }

            let plaintext = b"Data to encrypt and then tamper with.";
            let rust_handle = create_rust_aesgcm256_key();
            let (mut ciphertext, nonce) = rust_handle
                .encrypt_data(plaintext)
                .expect("Rust encrypt_data failed");
            // Tamper with ciphertext
            if !ciphertext.is_empty() {
                ciphertext[15] ^= 0xFF;
            }

            let rust_key = rust_handle
                .implementation
                .extract_key()
                .expect("Extract key failed");

            // libsodium decrypt => should fail
            unsafe {
                let mut decrypted = vec![0u8; ciphertext.len()];
                let mut dec_len: u64 = 0;
                let dec_res = crypto_aead_aes256gcm_decrypt(
                    decrypted.as_mut_ptr(),
                    &mut dec_len,
                    null_mut(),
                    ciphertext.as_ptr(),
                    ciphertext.len() as u64,
                    [].as_ptr(),
                    0,
                    nonce.as_ptr(),
                    rust_key.as_ptr(),
                );
                assert_ne!(
                    dec_res, 0,
                    "libsodium should fail to decrypt tampered ciphertext"
                );
            }
        }

        // ---------- 5) cross_check_id_method ----------
        #[test]
        fn cross_check_id_method() {
            init_sodium();

            let rust_handle = create_rust_aesgcm256_key();
            let key_id = rust_handle.id().expect("Failed to get key ID");
            assert!(!key_id.is_empty(), "Key ID should not be empty");
        }

        // ---------- 6) cross_check_encrypt_decrypt_large_data ----------
        #[test]
        fn cross_check_encrypt_decrypt_large_data() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available");
            }

            let plaintext = vec![0x61; 1_048_576]; // 1 MB
            let rust_handle = create_rust_aesgcm256_key();
            let (ciphertext, nonce) = rust_handle
                .encrypt_data(&plaintext)
                .expect("Encryption failed");
            let rust_key = rust_handle
                .implementation
                .extract_key()
                .expect("Failed to extract key");

            unsafe {
                let mut decrypted = vec![0u8; ciphertext.len()];
                let mut dec_len: u64 = 0;
                let dec_res = crypto_aead_aes256gcm_decrypt(
                    decrypted.as_mut_ptr(),
                    &mut dec_len,
                    null_mut(),
                    ciphertext.as_ptr(),
                    ciphertext.len() as u64,
                    [].as_ptr(),
                    0,
                    nonce.as_ptr(),
                    rust_key.as_ptr(),
                );
                assert_eq!(dec_res, 0, "libsodium decryption failed for large data");
                decrypted.truncate(dec_len as usize - MAX_TAG_LEN);

                assert_eq!(
                    from_utf8(&plaintext).unwrap(),
                    from_utf8(&decrypted).unwrap(),
                    "Decrypted data mismatch for large data"
                );
            }
        }

        // ---------- 7) cross_check_encrypt_same_plaintext_multiple_times ----------
        #[test]
        fn cross_check_encrypt_same_plaintext_multiple_times() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available");
            }

            let plaintext = b"Same plaintext encrypted multiple times with AES-GCM";
            let rust_handle = create_rust_aesgcm256_key();
            let rust_key = rust_handle
                .implementation
                .extract_key()
                .expect("Failed to extract raw key");
            // libsodium requires same key to decrypt

            // Encrypt #1
            let (ciphertext1, nonce1) = rust_handle
                .encrypt_data(plaintext)
                .expect("Encryption #1 failed");
            // Encrypt #2
            let (ciphertext2, nonce2) = rust_handle
                .encrypt_data(plaintext)
                .expect("Encryption #2 failed");

            // They should differ because of unique nonces
            assert_ne!(
                ciphertext1, ciphertext2,
                "Ciphertext should differ with different nonces"
            );

            // Decrypt #1 in libsodium
            unsafe {
                let mut dec1 = vec![0u8; ciphertext1.len()];
                let mut dec1_len: u64 = 0;
                let dec1_res = crypto_aead_aes256gcm_decrypt(
                    dec1.as_mut_ptr(),
                    &mut dec1_len,
                    null_mut(),
                    ciphertext1.as_ptr(),
                    ciphertext1.len() as u64,
                    [].as_ptr(),
                    0,
                    nonce1.as_ptr(),
                    rust_key.as_ptr(),
                );
                assert_eq!(dec1_res, 0, "Decryption #1 failed in libsodium");
                dec1.truncate(dec1_len as usize - MAX_TAG_LEN);
                assert_eq!(dec1, plaintext);

                // Decrypt #2
                let mut dec2 = vec![0u8; ciphertext2.len()];
                let mut dec2_len: u64 = 0;
                let dec2_res = crypto_aead_aes256gcm_decrypt(
                    dec2.as_mut_ptr(),
                    &mut dec2_len,
                    null_mut(),
                    ciphertext2.as_ptr(),
                    ciphertext2.len() as u64,
                    [].as_ptr(),
                    0,
                    nonce2.as_ptr(),
                    rust_key.as_ptr(),
                );
                assert_eq!(dec2_res, 0, "Decryption #2 failed in libsodium");
                dec2.truncate(dec2_len as usize - MAX_TAG_LEN);

                assert_eq!(dec2, plaintext);
            }
        }

        // ---------- 8) cross_check_decrypt_random_data ----------
        #[test]
        fn cross_check_decrypt_random_data() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available");
            }

            // Generate a real key in Rust
            let rust_handle = create_rust_aesgcm256_key();
            let rust_key = rust_handle
                .implementation
                .extract_key()
                .expect("Failed to extract key");
            // Create random "ciphertext"
            let mut random_data = vec![0u8; 50];
            unsafe {
                randombytes_buf(random_data.as_mut_ptr() as *mut c_void, random_data.len());
            }

            // libsodium attempts decryption => should fail
            unsafe {
                let mut dec = vec![0u8; random_data.len()];
                let mut dec_len: u64 = 0;
                let res = crypto_aead_aes256gcm_decrypt(
                    dec.as_mut_ptr(),
                    &mut dec_len,
                    null_mut(),
                    random_data.as_ptr(),
                    random_data.len() as u64,
                    [].as_ptr(),
                    0,
                    [0u8; 12].as_ptr(), // 12-byte zero nonce?
                    rust_key.as_ptr(),
                );
                // Usually fails
                assert_ne!(res, 0, "Decryption of random data should fail");
            }
        }

        // ---------- 9) cross_check_decrypt_short_data ----------
        #[test]
        fn cross_check_decrypt_short_data() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available");
            }

            // Key + short data
            let rust_handle = create_rust_aesgcm256_key();
            let rust_key = rust_handle
                .implementation
                .extract_key()
                .expect("Failed to extract key");
            let short_data = [0u8; 10]; // definitely too short

            // libsodium tries to decrypt => fail
            unsafe {
                let mut dec = vec![0u8; 10];
                let mut dec_len: u64 = 0;
                let res = crypto_aead_aes256gcm_decrypt(
                    dec.as_mut_ptr(),
                    &mut dec_len,
                    null_mut(),
                    short_data.as_ptr(),
                    short_data.len() as u64,
                    [].as_ptr(),
                    0,
                    [0u8; 12].as_ptr(),
                    rust_key.as_ptr(),
                );
                assert_ne!(res, 0, "Should fail with insufficient data");
            }
        }

        // ---------- 10) cross_check_encrypt_decrypt_different_cipher_spec ----------
        #[test]
        fn cross_check_encrypt_decrypt_different_cipher_spec() {
            init_sodium();
            // In libsodium, we only show AES-GCM-256.
            // For demonstration, we do Rust: "Encrypt with AesGcm256"
            // Then attempt to decrypt in Rust with "AesGcm128"
            // (But the cross-check piece is that libsodium also fails
            //  if the key length is mismatched, so you can do something similar
            //  if you store a 128-bit key in libsodium.)
            let plaintext = b"Testing encryption with different cipher specs";
            let rust_handle_256 = {
                let impl_config = unsafe { STORE.impl_config().clone() };
                let mut provider =
                    factory::create_provider_from_name("SoftwareProvider", impl_config)
                        .expect("Failed to create provider");
                let spec256 = KeySpec {
                    cipher: Cipher::AesGcm256,
                    ..Default::default()
                };
                provider
                    .create_key(spec256)
                    .expect("Create AesGcm256 failed")
            };

            let (ciphertext, nonce) = rust_handle_256
                .encrypt_data(plaintext)
                .expect("Encryption with AesGcm256 failed");

            // Rust handle with AesGcm128 tries to decrypt => fail
            let rust_handle_128 = {
                let impl_config = unsafe { STORE.impl_config().clone() };
                let mut provider =
                    factory::create_provider_from_name("SoftwareProvider", impl_config)
                        .expect("Failed to create provider");
                let spec128 = KeySpec {
                    cipher: Cipher::AesGcm128,
                    ..Default::default()
                };
                provider
                    .create_key(spec128)
                    .expect("Create AesGcm128 failed")
            };
            let dec_res = rust_handle_128.decrypt_data(&ciphertext, &nonce);
            assert!(
                dec_res.is_err(),
                "Decryption should fail with different cipher spec"
            );
        }

        // ---------- 11) cross_check_encrypt_decrypt_multiple_keys ----------
        #[test]
        fn cross_check_encrypt_decrypt_multiple_keys() {
            init_sodium();
            if unsafe { crypto_aead_aes256gcm_is_available() } == 0 {
                panic!("AES-GCM not available");
            }

            let plaintext = b"Testing multiple keys cross-check";
            // We'll create a few keys in Rust
            let rust_handles = (0..3)
                .map(|_| create_rust_aesgcm256_key())
                .collect::<Vec<_>>();

            for (i, handle) in rust_handles.iter().enumerate() {
                let (ciphertext, nonce) =
                    handle.encrypt_data(plaintext).expect("Encryption failed");
                let raw_key = handle
                    .implementation
                    .extract_key()
                    .expect("Extract key failed");

                // libsodium decrypt each
                unsafe {
                    let mut dec = vec![0u8; ciphertext.len()];
                    let mut dec_len: u64 = 0;
                    let dec_res = crypto_aead_aes256gcm_decrypt(
                        dec.as_mut_ptr(),
                        &mut dec_len,
                        null_mut(),
                        ciphertext.as_ptr(),
                        ciphertext.len() as u64,
                        [].as_ptr(),
                        0,
                        nonce.as_ptr(),
                        raw_key.as_ptr(),
                    );
                    assert_eq!(dec_res, 0, "libsodium decrypt failed for key #{}", i);
                    dec.truncate(dec_len as usize - MAX_TAG_LEN);
                    assert_eq!(&dec, plaintext, "Decrypted data mismatch for key #{}", i);
                }
            }
        }
    }

    // -------------------------------------------------------------------------
    // MODULE C: KEY DERIVATION CROSS-CHECK (XCHACHA20POLY1305)
    // -------------------------------------------------------------------------
    mod derive_key_cross_checks {
        use crate::common::{
            error::CalError,
            traits::{key_handle::KeyPairHandleImpl, module_provider::ProviderImpl},
        };

        use super::*;

        /// This yields a `KeyHandle` that internally uses a 32-byte XChaCha20Poly1305 key.
        fn derive_key_in_rust(password: &str, salt: &[u8]) -> Result<KeyHandle, CalError> {
            let impl_config = unsafe { STORE.impl_config().clone() };
            let mut provider = factory::create_provider_from_name("SoftwareProvider", impl_config)
                .expect("Failed to create provider");

            let spec = KeyPairSpec {
                asym_spec: AsymmetricKeySpec::Curve25519,
                cipher: Some(Cipher::XChaCha20Poly1305),
                signing_hash: CryptoHash::Sha2_256,
                ephemeral: true,
                non_exportable: false,
            };
            let key = provider
                .implementation
                .derive_key_from_password(password, salt, spec)?
                .implementation
                .extract_key()?;
            let sym_spec = KeySpec {
                cipher: Cipher::XChaCha20Poly1305,
                signing_hash: CryptoHash::Sha2_256,
                ephemeral: true,
            };
            provider.import_key(sym_spec, &key)
        }

        /// Derive a 32-byte key in libsodium via Argon2id, matching the same salt & password.
        unsafe fn derive_key_in_libsodium_argon2id(
            password: &str,
            salt: &[u8],
        ) -> Result<Vec<u8>, String> {
            if salt.len() != 16 {
                return Err(format!(
                    "Salt must be 16 bytes for this example, got {}",
                    salt.len()
                ));
            }
            let mut out_key = vec![0u8; 32];
            let res = crypto_pwhash_argon2id(
                out_key.as_mut_ptr(),
                out_key.len() as u64,
                password.as_ptr() as *const i8,
                password.len() as u64,
                salt.as_ptr(),
                OPSLIMIT,
                MEMLIMIT,
                ALG,
            );
            if res != 0 {
                return Err("libsodium pwhash Argon2id failed".to_string());
            }
            Ok(out_key)
        }

        /// Use libsodium to XChaCha20Poly1305-encrypt some plaintext with the derived key.
        unsafe fn xchacha20poly1305_encrypt_libsodium(
            key: &[u8],
            plaintext: &[u8],
        ) -> (Vec<u8>, Vec<u8>) {
            let mut nonce = vec![0u8; crypto_aead_xchacha20poly1305_ietf_NPUBBYTES as usize];
            randombytes_buf(nonce.as_mut_ptr() as *mut c_void, nonce.len());

            let mut ciphertext =
                vec![0u8; plaintext.len() + crypto_aead_xchacha20poly1305_ietf_ABYTES as usize];
            let mut ciphertext_len = 0u64;

            let ad = []; // no additional data

            let enc_res = crypto_aead_xchacha20poly1305_ietf_encrypt(
                ciphertext.as_mut_ptr(),
                &mut ciphertext_len,
                plaintext.as_ptr(),
                plaintext.len() as u64,
                ad.as_ptr(),
                ad.len() as u64,
                std::ptr::null_mut(),
                nonce.as_ptr(),
                key.as_ptr(),
            );
            assert_eq!(enc_res, 0, "libsodium xchacha encrypt failed");
            ciphertext.resize(ciphertext_len as usize, 0);

            (ciphertext, nonce)
        }

        /// Use libsodium to XChaCha20Poly1305-decrypt with the derived key.
        unsafe fn xchacha20poly1305_decrypt_libsodium(
            key: &[u8],
            ciphertext: &[u8],
            nonce: &[u8],
        ) -> Result<Vec<u8>, String> {
            let mut decrypted = vec![0u8; ciphertext.len()];
            let mut decrypted_len = 0u64;
            let ad = []; // no AAD

            let dec_res = crypto_aead_xchacha20poly1305_ietf_decrypt(
                decrypted.as_mut_ptr(),
                &mut decrypted_len,
                std::ptr::null_mut(),
                ciphertext.as_ptr(),
                ciphertext.len() as u64,
                ad.as_ptr(),
                ad.len() as u64,
                nonce.as_ptr(),
                key.as_ptr(),
            );
            if dec_res != 0 {
                return Err("libsodium xchacha decrypt failed".to_string());
            }
            decrypted.resize(decrypted_len as usize, 0);
            Ok(decrypted)
        }

        // ----------------------------------------------------------------------------
        // TESTS
        // ----------------------------------------------------------------------------

        #[test]
        fn cross_check_derive_key_success_and_same_key() {
            init_sodium();
            let password = "test_password";
            let salt = [0u8; 16];

            // 1) Derive in Rust
            let rust_keypair = derive_key_in_rust(password, &salt).expect("Rust derivation failed");
            let rust_key = rust_keypair
                .implementation
                .extract_key()
                .expect("Extract key from rust handle failed");
            assert_eq!(rust_key.len(), 32);

            // 2) Derive in libsodium
            let sodium_key = unsafe {
                derive_key_in_libsodium_argon2id(password, &salt)
                    .expect("libsodium Argon2id derivation failed")
            };
            assert_eq!(sodium_key.len(), 32);

            // If your Rust Argon2 params match libsodium’s, these should be the same:
            // If they differ, you can just check cross-encryption next.
            assert_eq!(
            rust_key, sodium_key,
            "Keys differ. Possibly param mismatch in Argon2? Ensure both sides match opslimit/memlimit."
        );
        }

        #[test]
        fn cross_check_derive_key_rust_encrypt_libsodium_decrypt() {
            init_sodium();
            let password = "test_password";
            let salt = [0u8; 16];
            let plaintext = b"Some data to encrypt with derived key in Rust, decrypt in libsodium";

            // Derive in Rust
            let rust_keypair = derive_key_in_rust(password, &salt).expect("Rust derivation failed");
            let rust_key = rust_keypair
                .implementation
                .extract_key()
                .expect("Extract Rust key failed");
            // Rust encrypt
            let (ciphertext, nonce) = rust_keypair
                .encrypt_data(plaintext)
                .expect("Rust xchacha encrypt_data failed");

            // libsodium decrypt
            let libsodium_decrypted = unsafe {
                xchacha20poly1305_decrypt_libsodium(&rust_key, &ciphertext, &nonce)
                    .expect("libsodium decrypt failed")
            };
            assert_eq!(
                libsodium_decrypted, plaintext,
                "libsodium decrypted text does not match original"
            );
        }

        #[test]
        fn cross_check_derive_key_libsodium_encrypt_rust_decrypt() {
            init_sodium();
            let password = "test_password";
            let salt = [0u8; 16];
            let plaintext = b"Some data to encrypt with derived key in libsodium, decrypt in Rust";

            // Derive in libsodium
            let libsodium_key = unsafe {
                derive_key_in_libsodium_argon2id(password, &salt)
                    .expect("libsodium Argon2id derivation failed")
            };

            // libsodium encrypt
            let (ciphertext, nonce) =
                unsafe { xchacha20poly1305_encrypt_libsodium(&libsodium_key, plaintext) };

            // Import libsodium key into Rust (since it's a symmetrical key for XChaCha20Poly1305)
            let impl_config = unsafe { STORE.impl_config().clone() };
            let mut provider = factory::create_provider_from_name("SoftwareProvider", impl_config)
                .expect("Failed to create provider for derived key import");

            let spec = KeySpec {
                cipher: Cipher::XChaCha20Poly1305,
                signing_hash: CryptoHash::Sha2_256,
                ephemeral: true,
            };

            let rust_keypair = provider
                .implementation
                .import_key(spec, &libsodium_key)
                .expect("Failed to import libsodium-derived key into Rust");

            // Rust decrypt
            let rust_decrypted = rust_keypair
                .decrypt_data(&ciphertext, &nonce)
                .expect("Rust decrypt_data failed");

            assert_eq!(
                rust_decrypted, plaintext,
                "Rust-decrypted text doesn't match original plaintext"
            );
        }

        #[test]
        fn cross_check_derive_key_different_passwords_yield_different_keys() {
            init_sodium();
            let salt = [0u8; 16];
            let password1 = "test_password";
            let password2 = "another_password";

            // Derive in Rust
            let rust_key1 = derive_key_in_rust(password1, &salt)
                .unwrap()
                .implementation
                .extract_key()
                .unwrap();
            let rust_key2 = derive_key_in_rust(password2, &salt)
                .unwrap()
                .implementation
                .extract_key()
                .unwrap();

            // Derive in libsodium
            let sodium_key1 =
                unsafe { derive_key_in_libsodium_argon2id(password1, &salt).unwrap() };
            let sodium_key2 =
                unsafe { derive_key_in_libsodium_argon2id(password2, &salt).unwrap() };

            assert_ne!(
                rust_key1, rust_key2,
                "Rust: Different passwords should yield different keys"
            );
            assert_ne!(
                sodium_key1, sodium_key2,
                "libsodium: Different passwords should yield different keys"
            );
        }

        #[test]
        fn cross_check_derive_key_different_salts_yield_different_keys() {
            init_sodium();
            let password = "test_password";
            let salt1 = [0u8; 16];
            let mut salt2 = [0u8; 16];
            salt2[0] = 1; // just so they differ

            // Derive in Rust
            let rust_key1 = derive_key_in_rust(password, &salt1)
                .unwrap()
                .implementation
                .extract_key()
                .unwrap();
            let rust_key2 = derive_key_in_rust(password, &salt2)
                .unwrap()
                .implementation
                .extract_key()
                .unwrap();

            // Derive in libsodium
            let sodium_key1 =
                unsafe { derive_key_in_libsodium_argon2id(password, &salt1).unwrap() };
            let sodium_key2 =
                unsafe { derive_key_in_libsodium_argon2id(password, &salt2).unwrap() };

            assert_ne!(
                rust_key1, rust_key2,
                "Rust: Different salts should yield different keys"
            );
            assert_ne!(
                sodium_key1, sodium_key2,
                "libsodium: Different salts should yield different keys"
            );
        }

        #[test]
        fn cross_check_derive_key_incorrect_salt_size_should_fail() {
            init_sodium();
            let password = "test_password";

            // If the code demands exactly 16 bytes, let's try 15 and 17:
            let salt_short = [0u8; 15];
            let salt_long = [0u8; 17];

            // Rust
            let result_short = derive_key_in_rust(password, &salt_short);
            assert!(
                result_short.is_err(),
                "Rust derive_key should fail with short salt"
            );
            let result_long = derive_key_in_rust(password, &salt_long);
            assert!(
                result_long.is_err(),
                "Rust derive_key should fail with long salt"
            );

            // libsodium
            unsafe {
                let lib_short = derive_key_in_libsodium_argon2id(password, &salt_short);
                assert!(
                    lib_short.is_err(),
                    "libsodium derivation should fail with short salt"
                );
                let lib_long = derive_key_in_libsodium_argon2id(password, &salt_long);
                assert!(
                    lib_long.is_err(),
                    "libsodium derivation should fail with long salt"
                );
            }
        }
    }
}
