// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'third_party/crypto_layer/common.dart';
import 'third_party/crypto_layer/common/config.dart';
import 'third_party/crypto_layer/common/crypto/algorithms.dart';
import 'third_party/crypto_layer/common/crypto/algorithms/encryption.dart';
import 'third_party/crypto_layer/common/crypto/algorithms/hashes.dart';
import 'third_party/crypto_layer/common/crypto/pkcs/standards.dart';
import 'third_party/crypto_layer/common/error.dart';
import 'third_party/crypto_layer/common/factory.dart';
import 'third_party/crypto_layer/common/traits/key_handle.dart';
import 'third_party/crypto_layer/common/traits/module_provider.dart';
import 'third_party/crypto_layer/stub.dart';
import 'third_party/crypto_layer/tpm/android/wrapper/key_store/cipher/jni.dart';
import 'third_party/crypto_layer/tpm/core/error.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_BoxProviderImplPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImplPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_AutoLocalPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstaticPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PinBoxFutureOutputBoxProviderImplAsyncTraitPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_traitPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PinBoxFutureOutputProviderConfigAsyncTraitPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_traitPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PinBoxFutureOutputResultBoxKeyHandleImplSecurityModuleErrorAsyncTraitPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_traitPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PinBoxFutureOutputResultDhExchangeSecurityModuleErrorAsyncTraitPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_traitPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PinBoxFutureOutputResultKeyHandleSecurityModuleErrorAsyncTraitPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_traitPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorAsyncTraitPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_traitPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_PinBoxFutureOutputResultVecU8SecurityModuleErrorAsyncTraitPtr =>
          wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_traitPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ProviderPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ProviderImplConfigPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfigPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SecurityModuleErrorPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleErrorPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_StubProviderPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderPtr;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_StubProviderFactoryPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactoryPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TpmErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmErrorPtr;

  @protected
  BoxProviderImpl
      dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
          dynamic raw);

  @protected
  AutoLocal
      dco_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
          dynamic raw);

  @protected
  PinBoxFutureOutputBoxProviderImplAsyncTrait
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputProviderConfigAsyncTrait
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultBoxKeyHandleImplSecurityModuleErrorAsyncTrait
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultDhExchangeSecurityModuleErrorAsyncTrait
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultKeyHandleSecurityModuleErrorAsyncTrait
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorAsyncTrait
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultVecU8SecurityModuleErrorAsyncTrait
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  Provider
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          dynamic raw);

  @protected
  ProviderImplConfig
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          dynamic raw);

  @protected
  SecurityModuleError
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
          dynamic raw);

  @protected
  StubProvider
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          dynamic raw);

  @protected
  StubProviderFactory
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          dynamic raw);

  @protected
  T dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
      dynamic raw);

  @protected
  TpmError
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          dynamic raw);

  @protected
  Provider
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          dynamic raw);

  @protected
  StubProvider
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          dynamic raw);

  @protected
  Provider
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          dynamic raw);

  @protected
  StubProvider
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          dynamic raw);

  @protected
  StubProviderFactory
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          dynamic raw);

  @protected
  TpmError
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          dynamic raw);

  @protected
  DHKeyExchangeImpl dco_decode_DynTrait_DHKeyExchangeImpl(dynamic raw);

  @protected
  KeyHandleImpl dco_decode_DynTrait_KeyHandleImpl(dynamic raw);

  @protected
  KeyPairHandleImpl dco_decode_DynTrait_KeyPairHandleImpl(dynamic raw);

  @protected
  AutoLocal
      dco_decode_Lifetimeable_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAutoLocalstaticstatic(
          dynamic raw);

  @protected
  BoxProviderImpl
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
          dynamic raw);

  @protected
  AutoLocal
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
          dynamic raw);

  @protected
  PinBoxFutureOutputBoxProviderImplAsyncTrait
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputProviderConfigAsyncTrait
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultBoxKeyHandleImplSecurityModuleErrorAsyncTrait
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultDhExchangeSecurityModuleErrorAsyncTrait
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultKeyHandleSecurityModuleErrorAsyncTrait
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorAsyncTrait
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  PinBoxFutureOutputResultVecU8SecurityModuleErrorAsyncTrait
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
          dynamic raw);

  @protected
  Provider
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          dynamic raw);

  @protected
  ProviderImplConfig
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          dynamic raw);

  @protected
  SecurityModuleError
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
          dynamic raw);

  @protected
  StubProvider
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          dynamic raw);

  @protected
  StubProviderFactory
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          dynamic raw);

  @protected
  T dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
      dynamic raw);

  @protected
  TpmError
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          dynamic raw);

  @protected
  Set<AsymmetricKeySpec> dco_decode_Set_asymmetric_key_spec(dynamic raw);

  @protected
  Set<Cipher> dco_decode_Set_cipher(dynamic raw);

  @protected
  Set<CryptoHash> dco_decode_Set_crypto_hash(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  DHKeyExchangeImpl dco_decode_TraitDef_DHKeyExchangeImpl(dynamic raw);

  @protected
  KeyHandleImpl dco_decode_TraitDef_KeyHandleImpl(dynamic raw);

  @protected
  KeyPairHandleImpl dco_decode_TraitDef_KeyPairHandleImpl(dynamic raw);

  @protected
  ProviderFactory dco_decode_TraitDef_ProviderFactory(dynamic raw);

  @protected
  ProviderImpl dco_decode_TraitDef_ProviderImpl(dynamic raw);

  @protected
  ToTpmError dco_decode_TraitDef_ToTpmError(dynamic raw);

  @protected
  AsymmetricKeySpec dco_decode_asymmetric_key_spec(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DHKeyExchangeImpl dco_decode_box_DynTrait_DHKeyExchangeImpl(dynamic raw);

  @protected
  KeyHandleImpl dco_decode_box_DynTrait_KeyHandleImpl(dynamic raw);

  @protected
  KeyPairHandleImpl dco_decode_box_DynTrait_KeyPairHandleImpl(dynamic raw);

  @protected
  Provider
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          dynamic raw);

  @protected
  Cipher dco_decode_box_autoadd_cipher(dynamic raw);

  @protected
  KeyHandle dco_decode_box_autoadd_key_handle(dynamic raw);

  @protected
  KeyPairHandle dco_decode_box_autoadd_key_pair_handle(dynamic raw);

  @protected
  KeyPairSpec dco_decode_box_autoadd_key_pair_spec(dynamic raw);

  @protected
  KeySpec dco_decode_box_autoadd_key_spec(dynamic raw);

  @protected
  ProviderConfig dco_decode_box_autoadd_provider_config(dynamic raw);

  @protected
  Cipher dco_decode_cipher(dynamic raw);

  @protected
  CryptoHash dco_decode_crypto_hash(dynamic raw);

  @protected
  DHExchange dco_decode_dh_exchange(dynamic raw);

  @protected
  DHKeyExchangeImplImplementor dco_decode_dh_key_exchange_impl_implementor(
      dynamic raw);

  @protected
  EccCurve dco_decode_ecc_curve(dynamic raw);

  @protected
  EccSigningScheme dco_decode_ecc_signing_scheme(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  KeyBits dco_decode_key_bits(dynamic raw);

  @protected
  KeyHandle dco_decode_key_handle(dynamic raw);

  @protected
  KeyHandleImplImplementor dco_decode_key_handle_impl_implementor(dynamic raw);

  @protected
  KeyPairHandle dco_decode_key_pair_handle(dynamic raw);

  @protected
  KeyPairHandleImplImplementor dco_decode_key_pair_handle_impl_implementor(
      dynamic raw);

  @protected
  KeyPairSpec dco_decode_key_pair_spec(dynamic raw);

  @protected
  KeySpec dco_decode_key_spec(dynamic raw);

  @protected
  List<ProviderImplConfig>
      dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          dynamic raw);

  @protected
  List<AsymmetricKeySpec> dco_decode_list_asymmetric_key_spec(dynamic raw);

  @protected
  List<Cipher> dco_decode_list_cipher(dynamic raw);

  @protected
  List<CryptoHash> dco_decode_list_crypto_hash(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  OidType dco_decode_oid_type(dynamic raw);

  @protected
  Provider?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          dynamic raw);

  @protected
  Cipher? dco_decode_opt_box_autoadd_cipher(dynamic raw);

  @protected
  ProviderConfig dco_decode_provider_config(dynamic raw);

  @protected
  SecurityLevel dco_decode_security_level(dynamic raw);

  @protected
  Sha2Bits dco_decode_sha_2_bits(dynamic raw);

  @protected
  Sha3Bits dco_decode_sha_3_bits(dynamic raw);

  @protected
  SymmetricMode dco_decode_symmetric_mode(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  BoxProviderImpl
      sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
          SseDeserializer deserializer);

  @protected
  AutoLocal
      sse_decode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputBoxProviderImplAsyncTrait
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputProviderConfigAsyncTrait
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultBoxKeyHandleImplSecurityModuleErrorAsyncTrait
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultDhExchangeSecurityModuleErrorAsyncTrait
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultKeyHandleSecurityModuleErrorAsyncTrait
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorAsyncTrait
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultVecU8SecurityModuleErrorAsyncTrait
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  Provider
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          SseDeserializer deserializer);

  @protected
  ProviderImplConfig
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          SseDeserializer deserializer);

  @protected
  SecurityModuleError
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
          SseDeserializer deserializer);

  @protected
  StubProvider
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          SseDeserializer deserializer);

  @protected
  StubProviderFactory
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          SseDeserializer deserializer);

  @protected
  T sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
      SseDeserializer deserializer);

  @protected
  TpmError
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          SseDeserializer deserializer);

  @protected
  Provider
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          SseDeserializer deserializer);

  @protected
  StubProvider
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          SseDeserializer deserializer);

  @protected
  Provider
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          SseDeserializer deserializer);

  @protected
  StubProvider
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          SseDeserializer deserializer);

  @protected
  StubProviderFactory
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          SseDeserializer deserializer);

  @protected
  TpmError
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          SseDeserializer deserializer);

  @protected
  DHKeyExchangeImpl sse_decode_DynTrait_DHKeyExchangeImpl(
      SseDeserializer deserializer);

  @protected
  KeyHandleImpl sse_decode_DynTrait_KeyHandleImpl(SseDeserializer deserializer);

  @protected
  KeyPairHandleImpl sse_decode_DynTrait_KeyPairHandleImpl(
      SseDeserializer deserializer);

  @protected
  AutoLocal
      sse_decode_Lifetimeable_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAutoLocalstaticstatic(
          SseDeserializer deserializer);

  @protected
  BoxProviderImpl
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
          SseDeserializer deserializer);

  @protected
  AutoLocal
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputBoxProviderImplAsyncTrait
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputProviderConfigAsyncTrait
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultBoxKeyHandleImplSecurityModuleErrorAsyncTrait
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultDhExchangeSecurityModuleErrorAsyncTrait
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultKeyHandleSecurityModuleErrorAsyncTrait
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorAsyncTrait
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  PinBoxFutureOutputResultVecU8SecurityModuleErrorAsyncTrait
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
          SseDeserializer deserializer);

  @protected
  Provider
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          SseDeserializer deserializer);

  @protected
  ProviderImplConfig
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          SseDeserializer deserializer);

  @protected
  SecurityModuleError
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
          SseDeserializer deserializer);

  @protected
  StubProvider
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          SseDeserializer deserializer);

  @protected
  StubProviderFactory
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          SseDeserializer deserializer);

  @protected
  T sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
      SseDeserializer deserializer);

  @protected
  TpmError
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          SseDeserializer deserializer);

  @protected
  Set<AsymmetricKeySpec> sse_decode_Set_asymmetric_key_spec(
      SseDeserializer deserializer);

  @protected
  Set<Cipher> sse_decode_Set_cipher(SseDeserializer deserializer);

  @protected
  Set<CryptoHash> sse_decode_Set_crypto_hash(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AsymmetricKeySpec sse_decode_asymmetric_key_spec(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DHKeyExchangeImpl sse_decode_box_DynTrait_DHKeyExchangeImpl(
      SseDeserializer deserializer);

  @protected
  KeyHandleImpl sse_decode_box_DynTrait_KeyHandleImpl(
      SseDeserializer deserializer);

  @protected
  KeyPairHandleImpl sse_decode_box_DynTrait_KeyPairHandleImpl(
      SseDeserializer deserializer);

  @protected
  Provider
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          SseDeserializer deserializer);

  @protected
  Cipher sse_decode_box_autoadd_cipher(SseDeserializer deserializer);

  @protected
  KeyHandle sse_decode_box_autoadd_key_handle(SseDeserializer deserializer);

  @protected
  KeyPairHandle sse_decode_box_autoadd_key_pair_handle(
      SseDeserializer deserializer);

  @protected
  KeyPairSpec sse_decode_box_autoadd_key_pair_spec(
      SseDeserializer deserializer);

  @protected
  KeySpec sse_decode_box_autoadd_key_spec(SseDeserializer deserializer);

  @protected
  ProviderConfig sse_decode_box_autoadd_provider_config(
      SseDeserializer deserializer);

  @protected
  Cipher sse_decode_cipher(SseDeserializer deserializer);

  @protected
  CryptoHash sse_decode_crypto_hash(SseDeserializer deserializer);

  @protected
  DHExchange sse_decode_dh_exchange(SseDeserializer deserializer);

  @protected
  DHKeyExchangeImplImplementor sse_decode_dh_key_exchange_impl_implementor(
      SseDeserializer deserializer);

  @protected
  EccCurve sse_decode_ecc_curve(SseDeserializer deserializer);

  @protected
  EccSigningScheme sse_decode_ecc_signing_scheme(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  KeyBits sse_decode_key_bits(SseDeserializer deserializer);

  @protected
  KeyHandle sse_decode_key_handle(SseDeserializer deserializer);

  @protected
  KeyHandleImplImplementor sse_decode_key_handle_impl_implementor(
      SseDeserializer deserializer);

  @protected
  KeyPairHandle sse_decode_key_pair_handle(SseDeserializer deserializer);

  @protected
  KeyPairHandleImplImplementor sse_decode_key_pair_handle_impl_implementor(
      SseDeserializer deserializer);

  @protected
  KeyPairSpec sse_decode_key_pair_spec(SseDeserializer deserializer);

  @protected
  KeySpec sse_decode_key_spec(SseDeserializer deserializer);

  @protected
  List<ProviderImplConfig>
      sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          SseDeserializer deserializer);

  @protected
  List<AsymmetricKeySpec> sse_decode_list_asymmetric_key_spec(
      SseDeserializer deserializer);

  @protected
  List<Cipher> sse_decode_list_cipher(SseDeserializer deserializer);

  @protected
  List<CryptoHash> sse_decode_list_crypto_hash(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OidType sse_decode_oid_type(SseDeserializer deserializer);

  @protected
  Provider?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          SseDeserializer deserializer);

  @protected
  Cipher? sse_decode_opt_box_autoadd_cipher(SseDeserializer deserializer);

  @protected
  ProviderConfig sse_decode_provider_config(SseDeserializer deserializer);

  @protected
  SecurityLevel sse_decode_security_level(SseDeserializer deserializer);

  @protected
  Sha2Bits sse_decode_sha_2_bits(SseDeserializer deserializer);

  @protected
  Sha3Bits sse_decode_sha_3_bits(SseDeserializer deserializer);

  @protected
  SymmetricMode sse_decode_symmetric_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
      sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
          BoxProviderImpl self, SseSerializer serializer);

  @protected
  void
      sse_encode_AutoExplicit_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
          AutoLocal self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
          PinBoxFutureOutputBoxProviderImplAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
          PinBoxFutureOutputProviderConfigAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultBoxKeyHandleImplSecurityModuleErrorAsyncTrait
              self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultDhExchangeSecurityModuleErrorAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultKeyHandleSecurityModuleErrorAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorAsyncTrait
              self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultVecU8SecurityModuleErrorAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          Provider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          ProviderImplConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
          SecurityModuleError self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          StubProvider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          StubProviderFactory self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
          T self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          TpmError self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          Provider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          StubProvider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          Provider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          StubProvider self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          StubProviderFactory self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          TpmError self, SseSerializer serializer);

  @protected
  void sse_encode_DynTrait_DHKeyExchangeImpl(
      DHKeyExchangeImpl self, SseSerializer serializer);

  @protected
  void sse_encode_DynTrait_KeyHandleImpl(
      KeyHandleImpl self, SseSerializer serializer);

  @protected
  void sse_encode_DynTrait_KeyPairHandleImpl(
      KeyPairHandleImpl self, SseSerializer serializer);

  @protected
  void
      sse_encode_Lifetimeable_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAutoLocalstaticstatic(
          AutoLocal self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
          BoxProviderImpl self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
          AutoLocal self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
          PinBoxFutureOutputBoxProviderImplAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
          PinBoxFutureOutputProviderConfigAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultBoxKeyHandleImplSecurityModuleErrorAsyncTrait
              self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultDhExchangeSecurityModuleErrorAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultKeyHandleSecurityModuleErrorAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorAsyncTrait
              self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
          PinBoxFutureOutputResultVecU8SecurityModuleErrorAsyncTrait self,
          SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          Provider self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          ProviderImplConfig self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
          SecurityModuleError self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
          StubProvider self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
          StubProviderFactory self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
          T self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
          TpmError self, SseSerializer serializer);

  @protected
  void sse_encode_Set_asymmetric_key_spec(
      Set<AsymmetricKeySpec> self, SseSerializer serializer);

  @protected
  void sse_encode_Set_cipher(Set<Cipher> self, SseSerializer serializer);

  @protected
  void sse_encode_Set_crypto_hash(
      Set<CryptoHash> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_asymmetric_key_spec(
      AsymmetricKeySpec self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_DynTrait_DHKeyExchangeImpl(
      DHKeyExchangeImpl self, SseSerializer serializer);

  @protected
  void sse_encode_box_DynTrait_KeyHandleImpl(
      KeyHandleImpl self, SseSerializer serializer);

  @protected
  void sse_encode_box_DynTrait_KeyPairHandleImpl(
      KeyPairHandleImpl self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          Provider self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cipher(Cipher self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_key_handle(
      KeyHandle self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_key_pair_handle(
      KeyPairHandle self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_key_pair_spec(
      KeyPairSpec self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_key_spec(KeySpec self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_provider_config(
      ProviderConfig self, SseSerializer serializer);

  @protected
  void sse_encode_cipher(Cipher self, SseSerializer serializer);

  @protected
  void sse_encode_crypto_hash(CryptoHash self, SseSerializer serializer);

  @protected
  void sse_encode_dh_exchange(DHExchange self, SseSerializer serializer);

  @protected
  void sse_encode_dh_key_exchange_impl_implementor(
      DHKeyExchangeImplImplementor self, SseSerializer serializer);

  @protected
  void sse_encode_ecc_curve(EccCurve self, SseSerializer serializer);

  @protected
  void sse_encode_ecc_signing_scheme(
      EccSigningScheme self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_key_bits(KeyBits self, SseSerializer serializer);

  @protected
  void sse_encode_key_handle(KeyHandle self, SseSerializer serializer);

  @protected
  void sse_encode_key_handle_impl_implementor(
      KeyHandleImplImplementor self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair_handle(KeyPairHandle self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair_handle_impl_implementor(
      KeyPairHandleImplImplementor self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair_spec(KeyPairSpec self, SseSerializer serializer);

  @protected
  void sse_encode_key_spec(KeySpec self, SseSerializer serializer);

  @protected
  void
      sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
          List<ProviderImplConfig> self, SseSerializer serializer);

  @protected
  void sse_encode_list_asymmetric_key_spec(
      List<AsymmetricKeySpec> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cipher(List<Cipher> self, SseSerializer serializer);

  @protected
  void sse_encode_list_crypto_hash(
      List<CryptoHash> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_oid_type(OidType self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
          Provider? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cipher(
      Cipher? self, SseSerializer serializer);

  @protected
  void sse_encode_provider_config(
      ProviderConfig self, SseSerializer serializer);

  @protected
  void sse_encode_security_level(SecurityLevel self, SseSerializer serializer);

  @protected
  void sse_encode_sha_2_bits(Sha2Bits self, SseSerializer serializer);

  @protected
  void sse_encode_sha_3_bits(Sha3Bits self, SseSerializer serializer);

  @protected
  void sse_encode_symmetric_mode(SymmetricMode self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImplPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImplPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImplPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImpl =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBoxdynProviderImplPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstaticPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstaticPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstaticPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstatic =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLifetimeableAutoLocalstaticstaticPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_trait =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputBoxdynProviderImplSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_trait =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputProviderConfigSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_trait =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultBoxdynKeyHandleImplSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_trait =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultDHExchangeSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_trait =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyHandleSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_trait =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultKeyPairHandleSecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_traitPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_trait =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPinBoxFutureOutputResultVecu8SecurityModuleErrorSendasync_traitPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfigPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfigPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfigPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfig =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerProviderImplConfigPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecurityModuleErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProvider =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactoryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactoryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactory =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStubProviderFactoryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerT =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_cal_flutter_plugin_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTpmErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
