name: Release

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: |
          npm i
          npm run build
      - name: Publish
        run: npx enhanced-publish --if-possible --use-preid-as-tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
